import { auth } from "@/auth";
import { SignOut } from "@/components/sign-out";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        {!session && <Link href="/login">Prihlasit sa </Link>}
        {!session && <Link href="/register"> Registrovat</Link>}
        {session && <SignOut />}
        <Link href="/">Hlavna stranka</Link>
        {children}
      </body>
    </html>
  );
}
